version: '3'

services:
  db:
    image: postgres:9.6
    volumes:
      - /private/var/postgresql/data:/var/lib/postgresql/data
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "80:8000"
    depends_on:
      - db