# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0003_auto_20170723_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='round.ScoreLine'),
        ),
    ]
