# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0004_auto_20170723_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoreline',
            name='points',
        ),
        migrations.AddField(
            model_name='scoreline',
            name='hole',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
