# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0005_auto_20170727_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='score_line',
        ),
        migrations.AddField(
            model_name='scoreline',
            name='score',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='round.Score'),
            preserve_default=False,
        ),
    ]
