# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0006_auto_20170727_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreline',
            name='strokes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
