# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreline',
            name='points',
            field=models.IntegerField(blank=True, null=True, verbose_name='Antal poäng'),
        ),
    ]
